export const IPC_CHANNELS = {
  THREAD_EVENT: "thread:event",
  THREAD_APPROVAL: "thread:approval",
  THREAD_STATUS: "thread:status",
  TERMINAL_DATA: "terminal:data",
  TERMINAL_EXIT: "terminal:exit",
  THREAD_CREATE: "thread:create",
  THREAD_DELETE: "thread:delete",
  THREAD_PROMPT: "thread:prompt",
  THREAD_APPROVE: "thread:approve",
  THREAD_CANCEL: "thread:cancel",
  THREAD_STEER: "thread:steer",
  THREAD_LIST: "thread:list",
  THREAD_RESTORE: "thread:restore",
  PROJECT_SELECT_DIR: "project:select-dir",
  PROJECT_GET: "project:get",
  TERMINAL_CREATE: "terminal:create",
  TERMINAL_INPUT: "terminal:input",
  TERMINAL_RESIZE: "terminal:resize",
  TERMINAL_DESTROY: "terminal:destroy",
} as const;
